import {Appointment, Contact} from '../models/appointments';

export const appointments: Appointment[] = [
  {
    id: 6,
    name: 'Eduardo Torres',
    address: 'Passeig de Gràcia 43, Barcelona',
    date: '2025-05-17',
    daysRemaining: 1,
    time: '16:00',
    subject: 'Puerta automática',
    description: 'Reparación de puerta automática de cochera',
    status: 'pending',
    priority: 'low',
    contactPhone: '655777889',
  },
  {
    id: 3,
    name: 'María López',
    address: 'Carrer de Balmes 103, Barcelona',
    date: '2025-05-10',
    daysRemaining: 3,
    time: '11:30',
    subject: 'Reparación de fuga',
    description: 'Fuga de agua en tubería principal del baño',
    status: 'pending',
    priority: 'high',
    contactPhone: '655987654',
  },
  {
    id: 2,
    name: 'Juan García',
    address: 'Rambla de Catalunya 33, Barcelona',
    date: '2025-05-07',
    daysRemaining: 6,
    time: '09:00',
    subject: 'Reparación eléctrica',
    description:
      'Falla en sistema eléctrico, luces parpadean intermitentemente',
    status: 'pending',
    priority: 'high',
    contactPhone: '655123456',
  },

  {
    id: 4,
    name: 'Roberto Méndez',
    address: 'Avinguda Diagonal 423, Barcelona',
    date: '2025-05-12',
    daysRemaining: 20,
    time: '14:00',
    subject: 'Instalación A/C',
    description: 'Instalación de nuevo aire acondicionado',
    status: 'pending',
    priority: 'medium',
    contactPhone: '633332211',
  },
  {
    id: 5,
    name: 'Lucía Fernández',
    address: 'Carrer de Mallorca 274, Barcelona',
    date: '2025-05-05',
    daysRemaining: 74,
    time: '10:00',
    subject: 'Revisión caldera',
    description: 'Revisión de caldera, no calienta agua adecuadamente',
    status: 'pending',
    priority: 'medium',
    contactPhone: '644455667',
  },
];

export const appointmentsHistory: Appointment[] = [
  {
    id: 7,
    name: 'Carmen Vega',
    address: "Carrer d'Aribau 185, Barcelona",
    date: '2025-01-20',
    daysRemaining: 0,
    time: '13:30',
    subject: 'Mantenimiento HVAC',
    description: 'Mantenimiento preventivo de sistema HVAC en oficina',
    status: 'pending',
    priority: 'medium',
    contactPhone: '622233445',
  },
  {
    id: 8,
    name: 'Fernando Soto',
    address: 'Passeig de Sant Joan 154, Barcelona',
    date: '2025-02-06',
    daysRemaining: 0,
    time: '08:00',
    subject: 'Instalación cámaras',
    description: 'Instalación de sistema de cámaras de seguridad',
    status: 'pending',
    priority: 'high',
    contactPhone: '688810102',
  },
  {
    id: 9,
    name: 'Patricia Ramírez',
    address: 'Carrer de Muntaner 259, Barcelona',
    date: '2025-03-22',
    daysRemaining: 0,
    time: '15:45',
    subject: 'Reparación lavadora',
    description: 'Lavadora no centrifuga correctamente',
    status: 'pending',
    priority: 'low',
    contactPhone: '666677889',
  },
  {
    id: 10,
    name: 'Alejandro Morales',
    address: 'Gran Via de les Corts Catalanes 579, Barcelona',
    date: '2025-04-15',
    daysRemaining: 0,
    time: '10:15',
    subject: 'Mantenimiento piscina',
    description: 'Limpieza y revisión de sistema de filtrado de piscina',
    status: 'pending',
    priority: 'medium',
    contactPhone: '611199005',
  },
];

export const contacts: Contact[] = [
  {
    id: 1,
    name: 'Jordi Valls',
    phone: '628653734',
    address: 'piso 4º puerta 2ª',
    additionalInfo: 'Disponible tardes y fines de semana',
    role: 'Técnico especialista en climatización',
  },
  {
    id: 2,
    name: 'Xavi Valls',
    phone: '660693632',
    address: 'Principal 1ª',
    additionalInfo: 'Contacto preferente para emergencias nocturnas',
    role: 'Supervisor de instalaciones eléctricas',
  },
  {
    id: 3,
    name: 'Carlos Sánchez',
    phone: '666677889',
    address: 'Piso 3º puerta 1ª',
    additionalInfo: 'Horario de atención: 9:00 - 18:00, L-V',
    role: 'Fontanero especialista',
  },
  {
    id: 4,
    name: 'Laura Martínez',
    phone: '644223355',
    address: 'piso 7º puerta 4ª',
    additionalInfo: 'Idiomas: Catalán, Castellano, Inglés',
    role: 'Atención al cliente',
  },
  {
    id: 5,
    name: 'Miguel Ferrer',
    phone: '622445566',
    address: 'piso 2º puerta 3ª',
    additionalInfo: 'Disponible para consultas técnicas',
    role: 'Ingeniero de sistemas',
  },
];
